---
title: "MATH 40024/50024: Computational Statistics, "
---

### Fall 2019 (Aug 22, 2019 - Dec 8, 2019)

__Lecture times:__ Mondays/Wednesdays/Fridays 11:00 am - 11:50am

__Location:__ MSB 158

__Instructor:__ Tsung-Heng Tsai | ttsai1@kent.edu | Office Hours: Thursday 2:00 pm - 3:00 pm or by appointment

__Administration:__ Questions and homework postings are handled via Piazza

__Textbooks:__ R for Data Science by Wickham and Grolemund, Advanced R by Wickham, 
Introduction to Data Science by Rafa Irrizary

__Academic integrity:__ Be familiar with the university’s academic integrity policy on cheating and plagiarism. (https://www.kent.edu/policyreg/administrative-policy-regarding-student-cheating-and-plagiarism)

__Syllabus:__ here. 

---

### Schedule 
_(subject to change)_

* __Week 0 (Fri Aug 23).__ Introduction.

* __Week 1 (Mon Aug 26 - Fri Aug 30).__ Basic data structures.

* __Week 2 (Mon Sept 02 - Fri Sept 06).__ Indexing and iteration.
_No class Monday: Labor Day._

* __Week 3 (Mon Sept 09 - Fri Sept 13).__ Text manipulation.

* __Week 4 (Mon Sept 16 - Fri Sept 20).__ Data frames and apply.

* __Week 5 (Mon Sept 23 - Fri Sept 27).__ Plotting. | Data visualization

* __Week 6 (Mon Sept 30 - Fri Oct 04).__ Functions.

* __Week 7 (Mon Oct 07 - Fri Oct 11).__ Simulation.
_No class Friday: Fall Break._

* __Week 8 (Mon Oct 14 - Fri Oct 18).__ Reading in data.

* __Week 9 (Mon Oct 21 - Fri Oct 25).__ Fitting models to data.

* __Week 10 (Mon Oct 28 - Fri Nov 01).__ Tidyverse I: Pipes and dplyr. | Data Transformation

* __Week 11 (Mon Nov 04 - Fri Nov 08).__ Tidyverse II: Tidyr and advanced dplyr. | Importing and tidying

* __Week 12 (Mon Nov 11 - Fri Nov 15).__ Debugging and testing.
_No class Monday: Veterans Day Observed._

* __Week 13 (Mon Nov 18 - Fri Nov 22).__ Version control and Git.

* __Week 14 (Mon Nov 25 - Fri Nov 29).__ Relational databases.
_No class Wednesday and Friday: Thanksgiving Break._

* __Week 15 (Mon Dec 02 - Fri Dec 06).__ Statistical prediction.

Introduction
- Course expectations
- Reproducible research
- R, Rstudio, Rmarkdown

1. R basics (2)
- Basic data structures
- Indexing and iteration
- Function
- Readable and efficient R code

2. Data visualization (1)
- ggplot2
- Layered grammar of graphics
- Practice and principle

3. Data transformation (2)
- Introduction to tidyverse
- dplyr
- Exploratory data analysis

4. Importing and tidying (2)
- Tidy data
- tidyr
- readr
- rvest?

5. (2) Data wrangling
- date-time
- factor
- string

6. (2) Random variable 
- Random number generator
- Simulation

7. (2) Probability and Statistics in R

8. (2) Optimization

9. (2) EM

10. (2) Markov chain Monte Carlo
- Gibbs
- Metropolis-Hastings

11. (2) Many models
- broom
- Model selection

12. (1) Resampling methods
- Bootstrap
- Jackknife

13. (2) Statistical prediction (machine learning)
- Training and test sets
- Feature selection (in the loop)
- Parameter tuning
- Cross-validation

14. (1) Unsupervised analysis [Thanksgiving]
- PCA
- SVD
- Clustering

15. (2) Reproducible research
- Git, GitHub
- R package
- Project management








EM

MCMC

Unsupervised analyiss

Functions, functional programming

Modeling

Many models
- broom



Optimization, EM

Simulation
- Random number generator

More simulation
- Markov chain Monte Carlo

Reproducible research (git, github, etc.)


Resampling methods



GIF: https://simplystatistics.org/2017/08/08/code-for-my-educational-gifs/

plots: 
https://hopstat.wordpress.com/2016/02/18/how-i-build-up-a-ggplot2-figure/
https://simplystatistics.org/2017/10/02/creating-an-expository-graph-for-a-talk/
https://www.biostat.wisc.edu/~kbroman/presentations/graphs2017.pdf

GWAS: https://simplystatistics.org/2017/06/20/lowering-the-gwas-threshold-would-save-millions-of-dollars/

datasets: 
https://simplystatistics.org/2018/01/22/the-dslabs-package-provides-datasets-for-teaching-data-science/
https://simplystatistics.org/2019/07/19/more-datasets-for-teaching-data-science-the-expanded-dslabs-package/

Hurricane:
https://simplystatistics.org/2017/12/03/data-do-not-agree-with-hurricane-official-death-count/
https://simplystatistics.org/2018/06/08/a-first-look-at-recently-released-official-puerto-rico-death-count-data/


---

This course is about the use of computational tools to manage, explore, summarize, and visualize data, as well as the computational underpinnings of fitting statistical models. It uses mostly the statistical computation language R, but also other languages like Python and Matlab. It also covers: simulation and random number generation, computationally intensive methods like the bootstrap and permutation tests, Expectation-Maximization and related algorithms, and dimensionality reduction via matrix decomposition.

Computationally intensive methods have become widely used in statistical inference. The objective of this course is to teach students important computational techniques used in statistical inference (evaluation of statistical methods, MLE and Bayesian inference). After learning this course, students are expected to gain understanding of algorithms behind statistical inferential methods, be able to develop new statistical methods, be able to use computer to investigate the properties of statistical methods, and be able to implement a combination of standard statistical toolkits for analyzing real data sets.

Computational data analysis is an essential part of modern statistics. Competent statisticians must not just be able to run existing programs, but to understand the principles on which they work. They must also be able to read, modify and write code, so that they can assemble the computational tools needed to solve their data-analysis problems, rather than distorting problems to fit tools provided by others. This class is an introduction to programming, targeted at statistics majors with minimal programming knowledge, which will give them the skills to grasp how statistical software works, tweak it to suit their needs, recombine existing pieces of code, and when needed create their own programs.

Students will learn the core of ideas of programming — functions, objects, data structures, flow control, input and output, debugging, logical design and abstraction — through writing code to assist in numerical and graphical statistical analyses. Students will in particular learn how to write maintainable code, and to test code for correctness. They will then learn how to set up stochastic simulations, how to parallelize data analyses, how to employ numerical optimization algorithms and diagnose their limitations, and how to work with and filter large data sets. Since code is also an important form of communication among scientists, students will learn how to comment and organize code.

The class will be taught in the R language.


Computational data analysis is an essential part of modern statistics. Competent statisticians must not just be able to run existing programs, but to understand the principles on which they work. They must also be able to read, modify, and write code, so that they can assemble the computational tools needed to solve their data analysis problems, rather than distorting problems to fit tools provided by others. This class is an introduction to statistically-oriented programming, targeted at statistics majors, without assuming extensive programming background.

Students will learn the core of ideas of programming—data structures, functions, iteration, input and output, debugging, logical design, and abstraction—through writing code to assist in statistical analyses. Students will learn how to write maintainable code, as well as debug and test code for correctness. They will learn how to set up and run stochastic simulations, how to fit basic statistical models and assess the results, and how to work with and filter large data sets. Since code is an important form of communication among scientists, students will also learn how to comment and organize code.

The class will be taught in the R programming language.

This course discusses the practical issues and techniques for data importing, tidying, transforming, and modeling. It offers a gentle introduction to techniques for processing big data. Programming is a cross-cutting aspect of the course. Students will gain experience with data science tools through short assignments. The course work includes a term project based on real-world data. Required topics include: Data management and processing: definition & background; Data transformation; Data import; Data cleaning; Data modeling; Relational and analytic databases; Basics of SQL; Programming in R; MapReduce fundamentals and distributed data management; Data processing pipelines, connecting multiple data management and analysis components; Interaction between the capabilities and requirements of data analysis methods (data structures, algorithms, memory requirements) and the choice of data storage and management tools; Repeatable and reproducible data analysis.

Computational statistics is a branch of mathematical sciences concerned with efficient methods for obtaining numerical solutions to statistically formulated problems. This course will introduce students to a variety of computationally intensive statistical techniques and the role of computation as a tool of discovery. Topics include numerical optimization in statistical inference [expectation-maximization (EM) algorithm, Fisher scoring, etc.], random number generation, Monte Carlo methods, randomization methods, jackknife methods, bootstrap methods, tools for identification of structure in data, estimation of functions (orthogonal polynomials, splines, etc.), and graphical methods. Additional topics may vary. Coursework will include computer assignments.

Classical statistical procedures arise where closed-form mathematical expressions are available for various inference summaries (e.g. linear regression; analysis of variance). A major emphasis of modern statistics is the development of inference principles in cases where both more complex data structures are involved and where more elaborate computations are required. Topics from numerical linear algebra, optimization, Monte Carlo (including Markov chain Monte Carlo), and graph theory are developed, especially as they relate to statistical inference (e.g., bootstrapping, permutation, Bayesian inference, EM algorithm, multivariate analysis).


---
Week1:
Simulating the distribution of the sample mean: function, script.
Illustration of underflow when computing likelihoods: script.
Using simulation to investigate effect of sample size: script.

Week2:
Finding zeros using bisection: functions. 
Finding zeros with Newton iteration: functions. 
Script using these functions: script.

Week3:
Multivariate Newton iteration: functions. 
Maximum likelihood estimate for a Poisson regression model: functions, script (now updated to include "method of scoring"). 
Maximum likelihood estimation of Poisson mean from interval data with nlm: function. 
Week5:
Integration using the midpoint rule: function (with tests), script (using knitr).
To use knitr, you must first install it with install.packages("knitr").
You can then use it with something like knitr::spin("midpoint-script.r").
This creates a file called midpoint-script.html which you can view in a browser.

Week 6:
Demo of transformation for integration: script.
Demo of multivariate integration: script.

Week 7:
EM for censored Poisson data: function, output of test.
EM for censored exponential data: function, output of test.

Week 8:
EM for mixture on binary data: function, test script.

Week 10:
Gibbs sampling for a simple random-effects model: R code.
Gibbs sampling for a latent Poisson process: R function.

Week 11:
Metropolis sampling for a simple Bayesian model: R code.


---

### Homework

---

### Exams

---

### Project

---

### Grading

---

### Supplementary materials

Supplementary textbooks on R programming:

* The R Cookbook, by Paul Teetor

* The R Graphics Cookbook, by Winston Chang

* The Art of R Programming: A Tour of Statistical Software Design, by Norman Matloff

* Software for Data Analysis: Programming with R, by John Chambers

* R for Data Science, by Hadley Wickham

Online resources for R programming:

* R Fundamentals and Programming Techniques, by Thomas Lumley

* Google's R Style Guide

* RStudio Cheat Sheets
