---
title: "CV"
---

---

### Education

* PhD, Electrical Engineering, Virginia Tech
* MS, Electrical and Control Engineering, National Chiao Tung University, Taiwan
* BS, Power Mechanical Engineering, National Tsing Hua University, Taiwan

### Employment

* Assistant Professor (2019-present), Department of Mathematical Sciences, Kent State University
* Postdoctoral Research Associate (2015-2019), Khoury College of Computer Sciences, Northeastern University
* Postdoctoral Research Fellow (2014-2015), Department of Translational Molecular Pathology, University of Texas MD Anderson Cancer Center
* Graduate Research Assistant (2009-2014), Department of Oncology, Georgetown Lombardi Comprehensive Cancer Center
* Research Assistant (2007-2009), Institute of Information Science, Academia Sinica

### Research Institutes and Initiatives

* Advanced Materials and Liquid Crystal Institute 
* Brain Health Research Institute

### Professional Activity

* Reviewer for Journals: _Bioinformatics_ (1), _BMC Bioinformatics_ (1), _Computational Statistics and Data Analysis_ (1), _EURASIP Journal on Bioinformatics and Systems Biology_ (1), _Frontiers in Cardiovascular Medicine_ (1), _IEEE/ACM Transactions on Computational Biology and Bioinformatics_ (3), _Journal of Applied Statistics_ (1), _Journal of Chromatography A_ (1), _Journal of Pharmacy and Pharmacology_ (1), _Molecular Systems Biology_ (1), _Nature Communications_ (1)
* Reviewer for Conferences: _BIBM_ (2013), _BMEI_ (2008), _ICASSP_ (2011, 2012), _iCBBE_ (2009), _ISBI_ (2011, 2012), _ISCAS_ (2011), _ISMB_ (2018), _MLSP_ (2011)
* Program Committee Member: _BIBM_ (2014, 2015, 2020, 2021), _ECCB_ (2020, 2022)

### Award

* William A. Blackwell Award, Virginia Tech (2014)
* Phi-Tau-Phi Honorary Member, National Chiao Tung University (2005)
* Mr. Feng-Chang Lu Memorial Scholarship, National Tsing Hua University (2002)
* Chun-Tsung Scholarship, Chun-Tsung Endowment (2002)
* Yung Tuan Memorial Scholarship, National Tsing Hua University (2001) 
