---
title: 'MATH 49995/57091: Introduction to Data Science'
output: html_document
---

### Spring 2020 (Jan 13, 2020 - Apr 28, 2020)

__Lecture times:__ Mondays and Wednesdays 2:15PM--3:30PM

__Location:__ MSB 158

__Instructor:__ Tsung-Heng Tsai | ttsai1@kent.edu | Office Hours: Mondays and Wednesdays 3:30PM--5PM or by appointment

__Textbooks:__ There is no required textbook but course notes will be provided throughout the course. Useful references are: 

1. (I2DS) [_Introduction to Data Science: Data Analysis and Prediction Algorithms with R_](https://rafalab.github.io/dsbook/), Rafael A. Irizarry, CRC Press, 1st Edition, 2019
2. (R4DS) [_R for Data Science: Import, Tidy, Transform, Visualize, and Model Data_](https://r4ds.had.co.nz), Hadley Wickham and Garrett Grolemund, O'Reilly Media, 1st Edition, 2017

Further reading will be recommended to support weekly class material.

__Plagiarism:__ Be familiar with the university's academic integrity policy on cheating and plagiarism. (https://www.kent.edu/policyreg/administrative-policy-regarding-student-cheating-and-plagiarism)

__Administration:__ [Syllabus](MATH57091-S20-syllabus.pdf), [Blackboard](https://learn.kent.edu/)

---

### Course Objectives

This course offers a gentle introduction to the field of data science. The goal of this course is to teach students how to answer questions with data. We will cover topics of data wrangling, exploratory data analysis, statistical inference and modeling, and statistical learning. We will also teach the necessary skills to gather, organize, explore and analyze data, and to develop data products to facilitate effective communication and reproducible research. The programming language R will be used extensively. The course will rely on the existing implementations of statistical methods in many cases, but some programming efforts will also be required. 

---

### Schedule 
_This schedule is tentative and subject to change._

- Mon Jan 13. Introduction to data science and the course
    + Reading: [50 Years of Data Science](https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1384734)
- Wed Jan 15. R, RStudio, R Markdown
    + Reading: R4DS "[Workflow: basics](https://r4ds.had.co.nz/workflow-basics.html)", R4DS "[R Markdown](https://r4ds.had.co.nz/r-markdown.html)", I2DS "[R basics](https://rafalab.github.io/dsbook/r-basics.html)"
- Mon Jan 20. _No class - Martin Luther King Jr. Day_
- Wed Jan 22. R basics
    + HW 1 out
    + Reading: R4DS "[Workflow: scripts](https://r4ds.had.co.nz/workflow-scripts.html)", R4DS "[Vectors](https://r4ds.had.co.nz/vectors.html)", I2DS "[R basics](https://rafalab.github.io/dsbook/r-basics.html)"
- Mon Jan 27. Functions
    + Reading: R4DS "[Functions](https://r4ds.had.co.nz/functions.html)", I2DS "[R basics](https://rafalab.github.io/dsbook/r-basics.html)", I2DS "[Programming basics](https://rafalab.github.io/dsbook/programming-basics.html)"
    + Optional: "[Lexical scoping](https://adv-r.hadley.nz/functions.html#lexical-scoping)", "[Lazy evaluation](https://adv-r.hadley.nz/functions.html#lazy-evaluation)", "[S3](https://adv-r.hadley.nz/s3.html)"
- Wed Jan 29. R basics
    + Reading: R4DS "[Iteration](https://r4ds.had.co.nz/iteration.html)", I2DS "[Programming basics](https://rafalab.github.io/dsbook/programming-basics.html)"
- Mon Feb 3. Layered grammar of graphics
    + HW 1 due
    + Reading: R4DS "[Data visualisation](https://r4ds.had.co.nz/data-visualisation.html)" 
- Wed Feb 5. Data visualization with ggplot2
    + Reading: R4DS "[Data visualisation](https://r4ds.had.co.nz/data-visualisation.html)", I2DS "[Data visualization in practice](https://rafalab.github.io/dsbook/gapminder.html)"
- Mon Feb 10. Principles of data visualization
    + Reading: I2DS "[Data visualization principles](https://rafalab.github.io/dsbook/data-visualization-principles.html)", R4DS "[Graphics for communication](https://r4ds.had.co.nz/graphics-for-communication.html)"
- Wed Feb 12. Data transformation
    + Reading: R4DS "[Data transformation](https://r4ds.had.co.nz/transform.html)", 
R4DS "[Tibbles](https://r4ds.had.co.nz/tibbles.html)", R4DS "[Pipes](https://r4ds.had.co.nz/pipes.html)"
- Mon Feb 17. Tidy data
    + Reading: R4DS "[Tidy data](https://r4ds.had.co.nz/tidy-data.html)"
- Wed Feb 19. Data importing
    + Reading: R4DS "[Data import](https://r4ds.had.co.nz/data-import.html)", I2DS "[Web scraping](https://rafalab.github.io/dsbook/web-scraping.html)"
- Mon Feb 24. Data wrangling
    + Reading: R4DS "[Strings](https://r4ds.had.co.nz/strings.html)", R4DS "[Factors](https://r4ds.had.co.nz/factors.html)", R4DS "[https://r4ds.had.co.nz/dates-and-times.html](Dates and times)"
- Wed Feb 26. Exploratory data analysis
    + Reading: R4DS "[Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html)"
- Mon Mar 2. Statistical inference
    + Reading: I2DS "[Statistical inference](https://rafalab.github.io/dsbook/inference.html)"
- Wed Mar 4. Resampling techniques
- Mon Mar 9. Review
- Wed Mar 11. Midterm exam (in class)
- Mon Mar 16. Statistical modeling
    + Reading: I2DS "[Statistical models](https://rafalab.github.io/dsbook/models.html)", R4DS "[Model basics](https://r4ds.had.co.nz/model-basics.html)", R4DS "[Model building](https://r4ds.had.co.nz/model-building.html)"
- Wed Mar 18. Advanced modeling
    + Reading: R4DS "[Many models](https://r4ds.had.co.nz/many-models.html)"
- Mon Mar 23. _No class - Spring Break_
- Wed Mar 25. _No class - Spring Break_
- Mon Mar 30. Version control, git, and GitHub
    + Reading: I2DS "[Git and GitHub](https://rafalab.github.io/dsbook/git.html)", [Happy Git and GitHub for the useR](https://happygitwithr.com/)
- Wed Apr 1. Building R Shiny apps
    + Reading: [Mastering Shiny](https://mastering-shiny.org/)"
- Mon Apr 6. Statistical prediction
    + Reading: I2DS "[Introduction to machine learning](https://rafalab.github.io/dsbook/introduction-to-machine-learning.html)"
- Wed Apr 8. Model evaluation and cross validation
    + Reading: I2DS "[Cross validation](https://rafalab.github.io/dsbook/cross-validation.html)", I2DS "[The caret package](https://rafalab.github.io/dsbook/caret.html)"
- Mon Apr 13. Dimensionality reduction
    + Reading: I2DS "[Large datasets](https://rafalab.github.io/dsbook/large-datasets.html)"
- Wed Apr 15. Clustering
    + Reading: I2DS "[Clustering](https://rafalab.github.io/dsbook/clustering.html)"
- Mon Apr 20. Databases
- Wed Apr 22. R package 
    + Reading: [R Packages](https://r-pkgs.org/)
- Mon Apr 27. Student presentations on final projects

---

### Grading

Grades will be calculated as follows:

* 6 homeworks: 30% (the lowest grade dropped)
* Midterm exam: 30%
* Final project: 40%

The final letter grades will follow the usual scale:

* 90--100 = A-range (i.e., A or A-)
* 80--89 = B-range (i.e., B+, B or B-)
* 70--79 = C-range (i.e., C+, C or C-)
* 60--69 = D
* 0--59 = F

The cutoffs for "+" and "-" will be determined at the end of the semester, at the discretion of the instructor. This scale is subject to change at the discretion of the instructor

### Homework

There will be six homework assignments. Each homework is due before class on the day it is listed, and should be completed in R Markdown format (with Rmd extension). An Rmd file contains a combination of content with simple text and R code chunks. Both the R Markdown source file and the resulting PDF output (generated by calling "Knit to PDF") must be turned in through Blackboard. 

Students may discuss and collaborate with friends, but your submitted work must be your own. Sharing of solutions will not be tolerated and will be considered cheating.

No late work will be accepted. Extensions may be given individually if requested at least 48 hours in advance of the due date with a reasonable justification. The lowest homework grade will be dropped.

### Exam

There will be an in-class midterm exam that counts for 30% of your grade. No collaboration with peers is allowed.

### Final project

There will be a final project that counts for 40% of your grade. More details will be posted and discussed later in the semester. 

---

### Supplementary materials

Supplementary textbooks: 

- [An Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/), by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/), by Garrett Grolemund
- [R Programming for Data Science](https://leanpub.com/rprogramming), by Roger D. Peng
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/), by Hadley Wickham
- [Advanced R](https://adv-r.hadley.nz), by Hadley Wickham
- [R Packages](https://r-pkgs.org/), by Hadley Wickham and Jennifer Bryan

Online resources for R programming:

- [An introduction to R](cran.r-project.org/doc/manuals/R-intro.html), by R Core Team
- [simpleR](cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf), by John Verzani
- [MATLAB / R Reference](http://www.math.umaine.edu/~hiebeler/comp/matlabR.pdf), by David Hiebeler
