---
title: "USEFUL LINKS"
---

---

### Courses

#### Programs

* Penn State Statistics Online: [web](https://online.stat.psu.edu/statprogram/) 


#### Statistical Computation

* Statistical Computation (Radford Neal): [web](http://www.utstat.utoronto.ca/~radford/sta410.F15/)

* Modern Computational Statistics (Cheng Zhang): [web](https://zcrabbit.github.io/courses/mcs-f19.html)

* Bayesian Theory and Computation (Cheng Zhang): [web](https://zcrabbit.github.io/courses/btc-s21.html) 

* An Introduction to Statistics in R: [web](http://petersonbiology.com/math230Notes/)

#### Statistical Theory

* Theory of Statistics: [web](https://www.math.arizona.edu/~jwatkins/stat566s20s.html)

* Mathematical Statistics: [web](https://ocw.mit.edu/courses/mathematics/18-655-mathematical-statistics-spring-2016/index.htm)

* Mathematical Statistics: [web](https://www.its.caltech.edu/~zuev/teaching/2013Spring/Math408.html)

* STAT 609: Mathematical Statistics I: [web](http://pages.stat.wisc.edu/~shao/stat609/main.html)

* STAT 709: Mathematical Statistics: [web](http://pages.stat.wisc.edu/~shao/stat709/main.html)

* STAT 710: Mathematical Statistics: [web](http://pages.stat.wisc.edu/~shao/stat710/main.html)

* Mathematical Statistics: [web](https://stat510.org/)


#### Statistical Methodology

* Analysis of Correlated Data: Mixed Linear Models: [web](https://02429.compute.dtu.dk/Frontpage)

* Linear and Generalized Linear Fixed and Mixed Effects Models: [web](https://dnett.github.io/S510/stat510.html)

* Repeated Measurements: [GitHub](https://github.com/drizopoulos/Repeated_Measurements), [slides](http://www.drizopoulos.com/courses/EMC/CE08.pdf) 

* Introduction to Statistical Methods: [web](https://www.math.arizona.edu/~jwatkins/data363s19s.html)

#### Introductory Statistics

* Statistics: [web](https://vanderbei.princeton.edu/245/Fall14/lectures.html)

#### Probability

* Statistics 110: Probability: [web](https://projects.iq.harvard.edu/stat110), [video](https://projects.iq.harvard.edu/stat110/youtube), [book](http://probabilitybook.net/), [book2](https://bookdown.org/probability/beta/)

* Introduction to Probability: [web](https://ocw.mit.edu/resources/res-6-012-introduction-to-probability-spring-2018/)

* Probabilistic Systems Analysis and Applied Probability: [web](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/)

* Fundamentals of Probability: [web](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-436j-fundamentals-of-probability-fall-2018/)

* Theory of Probability: [web](https://www.math.arizona.edu/~jwatkins/stat564f19.html)

* Introduction to Probability: [web](https://faculty.math.illinois.edu/~hildebr/461/)

* Actuarial Statistics I: [web](https://faculty.math.illinois.edu/~hildebr/408/)

#### Machine Learning

* Introduction to Machine Learning: [web](https://people.eecs.berkeley.edu/~jrs/189/)

* Full Stack Deep Learning: [web](https://fullstackdeeplearning.com/)

* Mathematics for Numerical Computing and Machine Learning
[web](https://www.cs.princeton.edu/courses/archive/spring21/cos302/)

* Introduction to Machine Learning: [web](https://www.cs.princeton.edu/courses/archive/spring19/cos324/)

#### Biostatistics and Computational Biology

* Biostatistics for Biomedical Research: [web](https://hbiostat.org/bbr/), [notes](http://hbiostat.org/doc/bbr.pdf)



#### Productivity

* The Missing Semester of Your CS Education: [web](https://missing.csail.mit.edu/), [video](https://www.youtube.com/playlist?list=PLyzOVJj3bHQuloKGG59rS43e29ro7I57J)

* LaTeX Tips: [web](https://faculty.math.illinois.edu/~hildebr/tex/tips.html)

#### Data

* Data Science in a Box: [web](https://datasciencebox.org/index.html)

* Advanced Data Science: [web](http://jtleek.com/ads2020/)

* Calling Bullshit: [web](https://callingbullshit.org/), [video](https://www.youtube.com/playlist?list=PLPnZfvKID1Sje5jWxt-4CSZD7bUI4gSPS) 

### Books

* [Introduction to Data Science: Data Analysis and Prediction Algorithms with R](https://rafalab.github.io/dsbook/) (Rafael A. Irizarry)
* [Modern Data Science with R](https://beanumber.github.io/mdsr2e/) (Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton)
* [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://r4ds.had.co.nz) (Hadley Wickham and Garrett Grolemund)
* [The Art of Machine Learning](http://heather.cs.ucdavis.edu/artofml/draft.pdf) (Norm Matloff)
* [From Linear Models to Machine Learning](http://heather.cs.ucdavis.edu/draftregclass.pdf)
* [Mathematical Foundations for Data Analysis](https://mathfordata.github.io/) (Jeff M. Phillips)
* [Mathematical Statistics: Old School](https://stat.istics.net/MathStat/) (John Marden)
* [Learning Theory from First Principles](https://www.di.ens.fr/~fbach/ltfp_book.pdf) (Francis Bach)
* [Probabilistic Machine Learning](https://probml.github.io/pml-book/) (Kevin Murphy)
* [Tidy Modeling with R](https://www.tmwr.org/) (Max Kuhn and Julia Silge)
* [Tidyverse Skills for Data Science](https://jhudatascience.org/tidyversecourse/) (Carrie Wright, Shannon E. Ellis, Stephanie C. Hicks and Roger D. Peng)
* [JABSTB: Statistical Design and Analysis of Experiments with R](https://tjmurphy.github.io/jabstb/) (TJ Murphy)
* [The Analysis of Biological Data](https://whitlockschluter3e.zoology.ubc.ca/index.html) (Michael Whitlock and Dolph Schluter)

### Statisticians / Data Scientists

* [Michael Clark](https://m-clark.github.io/)
* [Hadley Wickham](http://hadley.nz/)
* [Jenny Bryan](https://jennybryan.org/)
* [Rafael Irizarry](https://rafalab.github.io/)
* [Karl Broman](https://kbroman.org/)
* [Jeff Leek](http://jtleek.com/)
* [Andrew Gelman](http://www.stat.columbia.edu/~gelman/)
* [Frank Harrell](https://www.fharrell.com/)
* [Dimitris Rizopoulos](http://www.drizopoulos.com/)
* [Radford Neal](http://www.cs.utoronto.ca/~radford/)
* [Trevor Hastie](https://web.stanford.edu/~hastie/)
* [Ryan Tibshirani](https://www.stat.cmu.edu/~ryantibs/)
* [David Blei](http://www.cs.columbia.edu/~blei/)
* [John Marden](http://www.stat.istics.net/)

### Resources

#### Collections

* [Ten Simple Rules](https://collections.plos.org/collection/ten-simple-rules/)
* [Points of Significance](https://www.nature.com/collections/qghhqm/pointsofsignificance)
* [Data Science with R: A Resource Compendium](https://bookdown.org/martin_monkman/DataScienceResources_book/)
* [Big Book of R](https://www.bigbookofr.com/index.html)

#### Projects

* Steps toward reproducible research: [web](https://kbroman.org/steps2rr/), [video](https://www.youtube.com/watch?v=rNQ-RlG3JnQ&t=1025s)

* Project management

* Version control

* Bioconductor

#### Discussion sites

* [Datamethods](https://discourse.datamethods.org/) 
* [Stack Overflow](https://stackoverflow.com/)
* [RStudio Community](https://community.rstudio.com/)

### KSU

#### General

* [Guide To University Style](https://www.kent.edu/ucm/guide-university-style)

#### Sponsored Programs

* [Office of Sponsored Programs](https://www.kent.edu/research/sponsored-programs)
* [Proposal Resources](https://www.kent.edu/research/sponsored-programs/proposal-resources)
* [Kuali Research](https://www.kent.edu/research/sponsored-programs/kuali-research)

#### Grant Accounting

* [Grant Accounting](https://www.kent.edu/grantsaccounting)

### Grants

#### Templates

* [NIH Biosketch Template](https://www.overleaf.com/latex/templates/nih-biosketch-template/mtbcvhcmfpmw)
* [NIH Grant Template (2010)](https://www.overleaf.com/latex/templates/nih-grant-template-2010/xyyhdzpjzhfp)
* [LaTeX template for NSF-style Biographical Sketch](https://www.overleaf.com/latex/templates/latex-template-for-nsf-style-biographical-sketch/mqrkmftcmwrq)
* [NSF Grant Proposal Template](https://www.overleaf.com/latex/templates/nsf-grant-proposal-template/fmjvyntkcqmb)
* [NSF Grant Proposal LaTeX Template (MIT-MATH)](https://www.overleaf.com/latex/templates/nsf-grant-proposal-latex-template-mit-math/bpdgxygqdphw)

#### Writing

* [Leadership Lab: Writing Training](https://www.youtube.com/playlist?list=PLT9dtLV29xu8NkipEERDB2I62tLyhTJym)

#### Samples

#### Resources
