---
title: "PUBLICATIONS"
---

---

### Journal Papers

* J Bao, S Jegede, J Hawks, B Dade, Q Guan, S Middaugh, Z Qiu, A Levina, __T-H Tsai__ (2022). Detecting cochlear synaptopathy through curvature quantification of the auditory brainstem response. _Frontiers in Cellular Neuroscience_, 16:851500. [[Link](https://doi.org/10.3389/fncel.2022.851500)] 

* T Maculins, E Verschueren, T Hinkle, M Choi, P Chang, C Chalouni, S Rao, Y Kwon, J Lim, AK Katakam, RC Kunz, BK Erickson, T Huang, __T-H Tsai__, O Vitek, M Reichelt, Y Senbabaoglu, B Mckenzie, J Rohde, I Dikic, D Kirkpatrick, A Murthy (2021). Multiplexed proteomics of autophagy deficient murine macrophages reveals enhanced antimicrobial immunity via the oxidative stress response. _eLife_, 10:e62320. [[Link](https://elifesciences.org/articles/62320)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/34085925/)]

* A Arias-Alvarado, M Agayev, S Ilchenko, N Rachdaoui, J Lepp, __T-H Tsai__, G Zhang, S Previs, T Kasumov (2021). Measuring acetyl-CoA and acetylated histone turnover in vivo: effect of a high fat diet. _Analytical Biochemistry_, 615:114067. [[Link](https://doi.org/10.1016/j.ab.2020.114067)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/33340539/)]

* M Choi, J Carver, C Chiva, M Tzouros, T Huang, __T-H Tsai__, B Pullman, O Bernhardt, R Huttenhain, G Teo, Y Perez-Riverol, J Muntel, M Muller, S Goetze, M Pavlou, E Verschueren, B Wollscheid, A Nesvizhskii, L Reiter, T Dunkley, E Sabido, N Bandeira, O Vitek (2020). MassIVE.quant: a community resource of quantitative mass spectrometry-based proteomics datasets. _Nature Methods_, 17:981--984. [[Link](https://doi.org/10.1038/s41592-020-0955-0)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/32929271/)]

* __T-H Tsai__, M Choi, B Banfai, Y Liu, B. MacLean, T Dunkley, O Vitek (2020). Selection of features with consistent profiles improves relative protein quantification in mass spectrometry experiments. _Molecular & Cellular Proteomics_, 19(6):944--959. [[Link](https://doi.org/10.1074/mcp.ra119.001792)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/32234965/)]

* BV Sinn, C Fu, R Lau, J Litton, __T-H Tsai__, R Murthy, A Tam, E Andreopoulou, Y Gong, R Murthy, R Gould, Y Zhang, TA King, A Viale, V Andrade, D Giri, R Salgado, I Laios, C Sotiriou, C Marginean, DN Kwiatkowski, R Layman, D Booser, C Hatzis, V Valero, WF Symmans (2019). SET$_{\text{ER/PR}}$ - A robust 18-gene predictor for sensitivity to endocrine therapy for metastatic breast cancer. _npj Breast Cancer_, 5:16. [[Link](https://doi.org/10.1038/s41523-019-0111-0)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/31231679/)]

* __T-H Tsai__, Z Hao, Q Hong, B Moore, C Stella, JH Zhang, Y Chen, M Kim, T Koulis, GA Ryslik, E Verschueren, F Jacobson, WE Haskins, O Vitek (2017). Statistical characterization of therapeutic protein modifications. _Scientific Reports_, 7(1):7896. [[Link](https://doi.org/10.1038/s41598-017-08333-y)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/28801661/)]

* M Wang, __T-H Tsai__, C Di Poto, A Ferrarini, G Yu, HW Ressom (2016). Topic model-based mass spectrometric data analysis in cancer biomarker discovery studies. _BMC Genomics_, 17(Suppl 4):545. [[Link](https://doi.org/10.1186/s12864-016-2796-x)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/27535232/)]

* __T-H Tsai__, E Song, Z Rui, C Di Poto, M Wang, Y Luo, RS Varghese, MG Tadesse, DH Ziada, CS Desai, K Shetty, Y Mechref, HW Ressom (2015). LC-MS/MS based serum proteomics for identification of candidate biomarkers for hepatocellular carcinoma. _Proteomics_, 15(13):2369--2381. [[Link](https://doi.org/10.1002/pmic.201400364)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/25778709/)]

* __T-H Tsai__, M Wang, C Di Poto, Y Hu, S Zhou, Y Zhao, RS Varghese, Y Luo, MG Tadesse, DH Ziada, CS Desai, K Shetty, Y Mechref, HW Ressom (2014). LC-MS profiling of N-glycans derived from human serum samples for biomarker discovery in hepatocellular carcinoma. _Journal of Proteome Research_, 13(11):4859--4868. [[Link](https://doi.org/10.1021/pr500460k)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/25077556/)]

* __T-H Tsai__, MG Tadesse, C Di Poto, LK Pannell, Y Mechref, Y Wang, HW Ressom (2013). Multi-profile Bayesian alignment model for LC-MS data analysis with integration of internal standards. _Bioinformatics_, 29(21):2774--2780. [[Link](https://doi.org/10.1093/bioinformatics/btt461)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/24013927/)]

* __T-H Tsai__, MG Tadesse, Y Wang, HW Ressom (2013). Profile-based LC-MS data alignment --- A Bayesian approach. _IEEE/ACM Transactions on Computational Biology and Bioinformatics_, 10(2):494--503. [[Link](https://doi.org/10.1109/tcbb.2013.25)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/23929872/)]

* JF Xiao, RS Varghese, B Zhou, MR Ranjbar, Y Zhao, __T-H Tsai__, C Di Poto, J Wang, D Goerlitz, Y Luo, AK Cheema, N Sarhan, H Soliman, MG Tadesse, DH Ziada, HW Ressom (2012). LC-MS based serum metabolomics for identification of hepatocellular carcinoma biomarkers in Egyptian cohort. _Journal of Proteome Research_, 11(12):5914--5923. [[Link](https://doi.org/10.1021/pr300673x)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/23078175/)]

* HW Ressom, JF Xiao, L Tuli, RS Varghese, B Zhou, __T-H Tsai__, MR Ranjbar, Y Zhao, J Wang, C Di Poto, AK Cheema, MG Tadesse, R Goldman, K Shetty (2012). Utilization of metabolomics to identify serum biomarkers for hepatocellular carcinoma in patients with liver cirrhosis. _Analytica Chimica Acta_, 743:90--100. [[Link](https://doi.org/10.1016/j.aca.2012.07.013)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/22882828/)]

* L Tuli, __T-H Tsai__, RS Varghese, JF Xiao, AK Cheema, HW Ressom (2012). Using a spike-in experiment to evaluate analysis of LC-MS data. _Proteome Science_, 10(13). [[Link](https://doi.org/10.1186/1477-5956-10-13)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/22369182/)]

* GK Befekadu, MG Tadesse, __T-H Tsai__, HW Ressom (2011). Probabilistic mixture regression models for alignment of LC-MS data. _IEEE/ACM Transactions on Computational Biology and Bioinformatics_, 8(5):1417--1424. [[Link](https://doi.org/10.1109/tcbb.2010.88)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/20837998/)]

* T-T Liu, Y-H Lin, C-S Hung, T-J Liu, Y Chen, Y-C Huang, __T-H Tsai__, H-H Wang, D-W Wang, J-K Wang, Y-L Wang, C-H Lin (2009). A high speed detection platform based on surface-enhanced Raman scattering for monitoring antibiotic-induced chemical changes in bacteria cell wall. _PLoS One_, 4(5):e5470. [[Link](https://doi.org/10.1371/journal.pone.0005470)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/19421405/)]

* Y-H Yi, P-Y Ho, T-W Chen, W-J Lin, V Gukassyan, __T-H Tsai__, D-W Wang, T-S Liu, C-Y Tang, SJ Lo, T-Y Chen, F-J Kao, C-H Lin (2009). Membrane targeting and coupling of NHE1-integrin$\alpha_{\text{IIb}}\beta_{3}$-NCX1 by lipid rafts following integrin-ligand interactions trigger Ca$^{2+}$ oscillations. _Journal of Biological Chemistry_, 284(6):3855--3864. [[Link](https://doi.org/10.1074/jbc.m804334200)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/18996841/)]

### Book Chapters

* Y Fu, __T-H Tsai__, C Mao, SK Mun, HW Ressom, M Wang, Z Zhang, Y Wang (2020). Biological Computing. In _Biomedical Information Technology_ (Ed. D.D. Feng), Academic Press, pp. 81–104. [[Link](https://www.sciencedirect.com/science/article/pii/B9780128160343000031)]

* Y Zhao, __T-H Tsai__, C Di Poto, LK Pannell, MG Tadesse, HW Ressom (2017). Variability Assessment of Label-free LC-MS Experiments for Difference Detection. In _Statistical Analysis of Proteomics, Metabolomics and Lipidomics Data using Mass Spectrometry_ (Eds. S. Datta and B.J.A. Mertens), Springer, pp. 157--176. [[Link](https://link.springer.com/chapter/10.1007/978-3-319-45809-0_9)]

* __T-H Tsai__, M Wang, HW Ressom (2016). Preprocessing and Analysis of LC-MS-based Proteomic Data. In _Statistical Analysis in Proteomics_ (Ed. K. Jung), Springer, pp. 63--76. [[Link](https://dx.doi.org/10.1007/978-1-4939-3106-4_3)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/26519169/)]

